version: "3.8"
services:
    mongo:
        container_name: mongo
        build:
            context: ./mongo
            dockerfile: ./dockerfile
        restart: always
        ports:
            - 27018:27017
        volumes:
            - ./mongo/data:/data/db
            - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        env_file:
            - ./mongo/.env
    nest:
        container_name: nest
        build:
            context: ./nest
            dockerfile: ./dockerfile
        restart: always
        ports:
            - 3000:3000
        volumes:
            - ./nest/src:/app/src
        env_file:
            - ./nest/.env
